# This is a basic workflow to help you get started with Actions

name: Packer tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: packer test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Configure Authentication with GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: "latest"

      # - name: save .env files
      #   env:
      #     ENV_VAR: ${{ secrets.ENV_VAR }}
      #   run: echo "$ENV_VAR" > .env

      - name: creating zip
        run: |
          sudo apt install zip -y
          pwd
          ls -al 
          zip -r webapp.zip . -x '*packer*' -x '*.git*'

      - name: Run `packer init`
        id: init
        run: 
            |
            cd packer/
            packer init .

      - name: Run `packer fmt`
        id: fmt
        env: 
            PACKER_CONFIG: ${{secrets.PACKER_CONFIG}}
        run: |
            cd packer/
            packer fmt -check . 
            test $? -eq 0 || exit 1
            echo "$PACKER_CONFIG" > ./values.pkrvars.hcl
    
      - name: Run `packer validate`
        id: validate
        run: |
            cd packer/
            pwd
            packer validate -var-file="values.pkrvars.hcl" .
